package bav.astrobirthday.ui.common.opengl

import bav.astrobirthday.R
import kotlin.random.Random

sealed class TextureType(
    val minPlanetRadius: Float,
    val maxPlanetRadius: Float,
) {
    object Fungal : TextureType(0.5f, 2f)
    object GasGiant : TextureType(3f, 4f)
    object Ice : TextureType(0.5f, 1.5f)
    object Martian : TextureType(0.5f, 2f)
    object Oasis : TextureType(0.5f, 2f)
    object Oceanic : TextureType(0.5f, 2f)
    object Primordial : TextureType(0.5f, 2f)
    object Rock : TextureType(0.25f, 1f)
    object Swamp : TextureType(0.5f, 2f)
    object Terrestrial : TextureType(0.5f, 2f)
    object Volcanic : TextureType(0.25f, 1.5f)
    object Venusian : TextureType(0.5f, 2f)
    object Wetlands : TextureType(0.5f, 2f)
    object Unknown : TextureType(0f, 0f) // == random

    fun getRandomRadius(random: Random): Float {
        return minPlanetRadius + (maxPlanetRadius - minPlanetRadius) * random.nextFloat()
    }

    companion object {
        val allTypes = listOf(
            Fungal,
            GasGiant,
            Ice,
            Martian,
            Oasis,
            Oceanic,
            Primordial,
            Rock,
            Swamp,
            Terrestrial,
            Volcanic,
            Venusian,
            Wetlands,
        )

        val middleSizeTypes = listOf(
            Fungal,
            Martian,
            Oasis,
            Oceanic,
            Primordial,
            Swamp,
            Terrestrial,
            Volcanic,
            Venusian,
            Wetlands,
        )

        val smallSizeTypes = listOf(
            Ice,
            Rock
        )
    }
}

val fungalTextures = listOf(
    R.drawable.tex_fungal_1,
    R.drawable.tex_fungal_2,
    R.drawable.tex_fungal_3,
    R.drawable.tex_fungal_4,
    R.drawable.tex_fungal_5,
    R.drawable.tex_fungal_6,
    R.drawable.tex_fungal_7,
    R.drawable.tex_fungal_8,
    R.drawable.tex_fungal_9,
    R.drawable.tex_fungal_10,
    R.drawable.tex_fungal_11,
    R.drawable.tex_fungal_12,
    R.drawable.tex_fungal_13,
    R.drawable.tex_fungal_14,
    R.drawable.tex_fungal_15,
    R.drawable.tex_fungal_16,
)

val gasGiantTextures = listOf(
    R.drawable.tex_gas_giant_1,
    R.drawable.tex_gas_giant_2,
    R.drawable.tex_gas_giant_3,
    R.drawable.tex_gas_giant_4,
    R.drawable.tex_gas_giant_5,
    R.drawable.tex_gas_giant_6,
    R.drawable.tex_gas_giant_7,
    R.drawable.tex_gas_giant_8,
    R.drawable.tex_gas_giant_9,
    R.drawable.tex_gas_giant_10,
    R.drawable.tex_gas_giant_11,
    R.drawable.tex_gas_giant_12,
    R.drawable.tex_gas_giant_13,
    R.drawable.tex_gas_giant_14,
    R.drawable.tex_gas_giant_15,
    R.drawable.tex_gas_giant_16,
    R.drawable.tex_gas_giant_17,
    R.drawable.tex_gas_giant_18,
    R.drawable.tex_gas_giant_19,
    R.drawable.tex_gas_giant_20,
    R.drawable.tex_gas_giant_21,
    R.drawable.tex_gas_giant_22,
    R.drawable.tex_gas_giant_23,
    R.drawable.tex_gas_giant_24,
    R.drawable.tex_gas_giant_25,
    R.drawable.tex_gas_giant_26,
    R.drawable.tex_gas_giant_27,
    R.drawable.tex_gas_giant_28,
    R.drawable.tex_gas_giant_29,
    R.drawable.tex_gas_giant_30,
    R.drawable.tex_gas_giant_31,
    R.drawable.tex_gas_giant_32,
)

val iceTextures = listOf(
    R.drawable.tex_ice_1,
    R.drawable.tex_ice_2,
    R.drawable.tex_ice_3,
    R.drawable.tex_ice_4,
    R.drawable.tex_ice_5,
    R.drawable.tex_ice_6,
    R.drawable.tex_ice_7,
    R.drawable.tex_ice_8,
    R.drawable.tex_ice_9,
    R.drawable.tex_ice_10,
    R.drawable.tex_ice_11,
    R.drawable.tex_ice_12,
    R.drawable.tex_ice_13,
    R.drawable.tex_ice_14,
    R.drawable.tex_ice_15,
    R.drawable.tex_ice_16,
    R.drawable.tex_ice_17,
    R.drawable.tex_ice_18,
    R.drawable.tex_ice_19,
    R.drawable.tex_ice_20,
    R.drawable.tex_ice_21,
    R.drawable.tex_ice_22,
    R.drawable.tex_ice_23,
    R.drawable.tex_ice_24,
    R.drawable.tex_ice_25,
    R.drawable.tex_ice_26,
    R.drawable.tex_ice_27,
    R.drawable.tex_ice_28,
    R.drawable.tex_ice_29,
    R.drawable.tex_ice_30,
    R.drawable.tex_ice_31,
    R.drawable.tex_ice_32,
)

val martianTextures = listOf(
    R.drawable.tex_martian_1,
    R.drawable.tex_martian_2,
    R.drawable.tex_martian_3,
    R.drawable.tex_martian_4,
    R.drawable.tex_martian_5,
    R.drawable.tex_martian_6,
    R.drawable.tex_martian_7,
    R.drawable.tex_martian_8,
    R.drawable.tex_martian_9,
    R.drawable.tex_martian_10,
    R.drawable.tex_martian_11,
    R.drawable.tex_martian_12,
    R.drawable.tex_martian_13,
    R.drawable.tex_martian_14,
    R.drawable.tex_martian_15,
    R.drawable.tex_martian_16,
    R.drawable.tex_martian_17,
    R.drawable.tex_martian_18,
    R.drawable.tex_martian_19,
    R.drawable.tex_martian_20,
    R.drawable.tex_martian_21,
    R.drawable.tex_martian_22,
    R.drawable.tex_martian_23,
    R.drawable.tex_martian_24,
)

val oasisTextures = listOf(
    R.drawable.tex_oasis_1,
    R.drawable.tex_oasis_2,
    R.drawable.tex_oasis_3,
    R.drawable.tex_oasis_4,
    R.drawable.tex_oasis_5,
    R.drawable.tex_oasis_6,
    R.drawable.tex_oasis_7,
    R.drawable.tex_oasis_8,
    R.drawable.tex_oasis_9,
    R.drawable.tex_oasis_10,
    R.drawable.tex_oasis_11,
    R.drawable.tex_oasis_12,
    R.drawable.tex_oasis_13,
    R.drawable.tex_oasis_14,
    R.drawable.tex_oasis_15,
    R.drawable.tex_oasis_16,
)

val oceanicTextures = listOf(
    R.drawable.tex_oceanic_1,
    R.drawable.tex_oceanic_2,
    R.drawable.tex_oceanic_3,
    R.drawable.tex_oceanic_4,
    R.drawable.tex_oceanic_5,
    R.drawable.tex_oceanic_6,
    R.drawable.tex_oceanic_7,
    R.drawable.tex_oceanic_8,
    R.drawable.tex_oceanic_clouds_9,
    R.drawable.tex_oceanic_clouds_10,
    R.drawable.tex_oceanic_clouds_11,
    R.drawable.tex_oceanic_clouds_12,
    R.drawable.tex_oceanic_clouds_13,
    R.drawable.tex_oceanic_clouds_14,
    R.drawable.tex_oceanic_clouds_15,
    R.drawable.tex_oceanic_clouds_16,
)

val primordialTextures = listOf(
    R.drawable.tex_primordial_1,
    R.drawable.tex_primordial_2,
    R.drawable.tex_primordial_3,
    R.drawable.tex_primordial_4,
    R.drawable.tex_primordial_5,
    R.drawable.tex_primordial_6,
    R.drawable.tex_primordial_7,
    R.drawable.tex_primordial_8,
    R.drawable.tex_primordial_9,
    R.drawable.tex_primordial_10,
    R.drawable.tex_primordial_11,
    R.drawable.tex_primordial_12,
    R.drawable.tex_primordial_13,
    R.drawable.tex_primordial_14,
    R.drawable.tex_primordial_15,
    R.drawable.tex_primordial_16,
    R.drawable.tex_primordial_17,
    R.drawable.tex_primordial_18,
    R.drawable.tex_primordial_19,
    R.drawable.tex_primordial_20,
    R.drawable.tex_primordial_21,
    R.drawable.tex_primordial_22,
    R.drawable.tex_primordial_23,
    R.drawable.tex_primordial_24,
    R.drawable.tex_primordial_25,
    R.drawable.tex_primordial_26,
    R.drawable.tex_primordial_27,
    R.drawable.tex_primordial_28,
    R.drawable.tex_primordial_29,
    R.drawable.tex_primordial_30,
    R.drawable.tex_primordial_31,
    R.drawable.tex_primordial_32,
)

val rockTextures = listOf(
    R.drawable.tex_rock_1,
    R.drawable.tex_rock_2,
    R.drawable.tex_rock_3,
    R.drawable.tex_rock_4,
    R.drawable.tex_rock_5,
    R.drawable.tex_rock_6,
    R.drawable.tex_rock_7,
    R.drawable.tex_rock_8,
    R.drawable.tex_rock_9,
    R.drawable.tex_rock_10,
    R.drawable.tex_rock_11,
    R.drawable.tex_rock_12,
    R.drawable.tex_rock_13,
    R.drawable.tex_rock_14,
    R.drawable.tex_rock_15,
    R.drawable.tex_rock_16,
    R.drawable.tex_rock_17,
    R.drawable.tex_rock_18,
    R.drawable.tex_rock_19,
    R.drawable.tex_rock_20,
    R.drawable.tex_rock_21,
    R.drawable.tex_rock_22,
    R.drawable.tex_rock_23,
    R.drawable.tex_rock_24,
)

val swampTextures = listOf(
    R.drawable.tex_swamp_1,
    R.drawable.tex_swamp_2,
    R.drawable.tex_swamp_3,
    R.drawable.tex_swamp_4,
    R.drawable.tex_swamp_5,
    R.drawable.tex_swamp_6,
    R.drawable.tex_swamp_7,
    R.drawable.tex_swamp_8,
    R.drawable.tex_swamp_clouds_9,
    R.drawable.tex_swamp_clouds_10,
    R.drawable.tex_swamp_clouds_11,
    R.drawable.tex_swamp_clouds_12,
    R.drawable.tex_swamp_clouds_13,
    R.drawable.tex_swamp_clouds_14,
    R.drawable.tex_swamp_clouds_15,
    R.drawable.tex_swamp_clouds_16,
)

val terrestrialTextures = listOf(
    R.drawable.tex_terrestrial_1,
    R.drawable.tex_terrestrial_2,
    R.drawable.tex_terrestrial_3,
    R.drawable.tex_terrestrial_4,
    R.drawable.tex_terrestrial_5,
    R.drawable.tex_terrestrial_6,
    R.drawable.tex_terrestrial_7,
    R.drawable.tex_terrestrial_8,
    R.drawable.tex_terrestrial_9,
    R.drawable.tex_terrestrial_10,
    R.drawable.tex_terrestrial_11,
    R.drawable.tex_terrestrial_12,
    R.drawable.tex_terrestrial_13,
    R.drawable.tex_terrestrial_14,
    R.drawable.tex_terrestrial_15,
    R.drawable.tex_terrestrial_16,
    R.drawable.tex_terrestrial_clouds_17,
    R.drawable.tex_terrestrial_clouds_18,
    R.drawable.tex_terrestrial_clouds_19,
    R.drawable.tex_terrestrial_clouds_20,
    R.drawable.tex_terrestrial_clouds_21,
    R.drawable.tex_terrestrial_clouds_22,
    R.drawable.tex_terrestrial_clouds_23,
    R.drawable.tex_terrestrial_clouds_24,
    R.drawable.tex_terrestrial_clouds_25,
    R.drawable.tex_terrestrial_clouds_26,
    R.drawable.tex_terrestrial_clouds_27,
    R.drawable.tex_terrestrial_clouds_28,
    R.drawable.tex_terrestrial_clouds_29,
    R.drawable.tex_terrestrial_clouds_30,
    R.drawable.tex_terrestrial_clouds_31,
    R.drawable.tex_terrestrial_clouds_32,
)

val volcanicTextures = listOf(
    R.drawable.tex_volcanic_1,
    R.drawable.tex_volcanic_2,
    R.drawable.tex_volcanic_3,
    R.drawable.tex_volcanic_4,
    R.drawable.tex_volcanic_5,
    R.drawable.tex_volcanic_6,
    R.drawable.tex_volcanic_7,
    R.drawable.tex_volcanic_8,
    R.drawable.tex_volcanic_9,
    R.drawable.tex_volcanic_10,
    R.drawable.tex_volcanic_11,
    R.drawable.tex_volcanic_12,
    R.drawable.tex_volcanic_13,
    R.drawable.tex_volcanic_14,
    R.drawable.tex_volcanic_15,
    R.drawable.tex_volcanic_16,
)

val venusianTextures = listOf(
    R.drawable.tex_venusian_1,
    R.drawable.tex_venusian_2,
    R.drawable.tex_venusian_3,
    R.drawable.tex_venusian_4,
    R.drawable.tex_venusian_5,
    R.drawable.tex_venusian_6,
    R.drawable.tex_venusian_7,
    R.drawable.tex_venusian_8,
    R.drawable.tex_venusian_9,
    R.drawable.tex_venusian_10,
    R.drawable.tex_venusian_11,
    R.drawable.tex_venusian_12,
    R.drawable.tex_venusian_13,
    R.drawable.tex_venusian_14,
    R.drawable.tex_venusian_15,
    R.drawable.tex_venusian_16,
)

val wetlandsTextures = listOf(
    R.drawable.tex_wetlands_1,
    R.drawable.tex_wetlands_2,
    R.drawable.tex_wetlands_3,
    R.drawable.tex_wetlands_4,
    R.drawable.tex_wetlands_5,
    R.drawable.tex_wetlands_6,
    R.drawable.tex_wetlands_7,
    R.drawable.tex_wetlands_8,
    R.drawable.tex_wetlands_clouds_9,
    R.drawable.tex_wetlands_clouds_10,
    R.drawable.tex_wetlands_clouds_11,
    R.drawable.tex_wetlands_clouds_12,
    R.drawable.tex_wetlands_clouds_13,
    R.drawable.tex_wetlands_clouds_14,
    R.drawable.tex_wetlands_clouds_15,
    R.drawable.tex_wetlands_clouds_16,
)

val satelliteTextures = listOf(
    R.drawable.tex_ice_satellite_1,
    R.drawable.tex_ice_satellite_2,
    R.drawable.tex_ice_satellite_3,
    R.drawable.tex_rock_satellite_1,
    R.drawable.tex_rock_satellite_2,
    R.drawable.tex_rock_satellite_3,
)

val ringTextures = listOf(
    R.drawable.tex_ring_50,
)

val allPlanetTextures = listOf(
    fungalTextures,
    gasGiantTextures,
    iceTextures,
    martianTextures,
    oasisTextures,
    oceanicTextures,
    primordialTextures,
    rockTextures,
    swampTextures,
    terrestrialTextures,
    volcanicTextures,
    venusianTextures,
    wetlandsTextures,
)

val allPlanetTexturesFlatten = allPlanetTextures.flatten()

val planetImagesByTextureId = mapOf(
    R.drawable.tex_fungal_1 to R.drawable.img_fungal_1_crop,
    R.drawable.tex_fungal_2 to R.drawable.img_fungal_2_crop,
    R.drawable.tex_fungal_3 to R.drawable.img_fungal_3_crop,
    R.drawable.tex_fungal_4 to R.drawable.img_fungal_4_crop,
    R.drawable.tex_fungal_5 to R.drawable.img_fungal_5_crop,
    R.drawable.tex_fungal_6 to R.drawable.img_fungal_6_crop,
    R.drawable.tex_fungal_7 to R.drawable.img_fungal_7_crop,
    R.drawable.tex_fungal_8 to R.drawable.img_fungal_8_crop,
    R.drawable.tex_fungal_9 to R.drawable.img_fungal_9_crop,
    R.drawable.tex_fungal_10 to R.drawable.img_fungal_10_crop,
    R.drawable.tex_fungal_11 to R.drawable.img_fungal_11_crop,
    R.drawable.tex_fungal_12 to R.drawable.img_fungal_12_crop,
    R.drawable.tex_fungal_13 to R.drawable.img_fungal_13_crop,
    R.drawable.tex_fungal_14 to R.drawable.img_fungal_14_crop,
    R.drawable.tex_fungal_15 to R.drawable.img_fungal_15_crop,
    R.drawable.tex_fungal_16 to R.drawable.img_fungal_16_crop,

    R.drawable.tex_gas_giant_1 to R.drawable.img_gas_giant_1_crop,
    R.drawable.tex_gas_giant_2 to R.drawable.img_gas_giant_2_crop,
    R.drawable.tex_gas_giant_3 to R.drawable.img_gas_giant_3_crop,
    R.drawable.tex_gas_giant_4 to R.drawable.img_gas_giant_4_crop,
    R.drawable.tex_gas_giant_5 to R.drawable.img_gas_giant_5_crop,
    R.drawable.tex_gas_giant_6 to R.drawable.img_gas_giant_6_crop,
    R.drawable.tex_gas_giant_7 to R.drawable.img_gas_giant_7_crop,
    R.drawable.tex_gas_giant_8 to R.drawable.img_gas_giant_8_crop,
    R.drawable.tex_gas_giant_9 to R.drawable.img_gas_giant_9_crop,
    R.drawable.tex_gas_giant_10 to R.drawable.img_gas_giant_10_crop,
    R.drawable.tex_gas_giant_11 to R.drawable.img_gas_giant_11_crop,
    R.drawable.tex_gas_giant_12 to R.drawable.img_gas_giant_12_crop,
    R.drawable.tex_gas_giant_13 to R.drawable.img_gas_giant_13_crop,
    R.drawable.tex_gas_giant_14 to R.drawable.img_gas_giant_14_crop,
    R.drawable.tex_gas_giant_15 to R.drawable.img_gas_giant_15_crop,
    R.drawable.tex_gas_giant_16 to R.drawable.img_gas_giant_16_crop,
    R.drawable.tex_gas_giant_17 to R.drawable.img_gas_giant_17_crop,
    R.drawable.tex_gas_giant_18 to R.drawable.img_gas_giant_18_crop,
    R.drawable.tex_gas_giant_19 to R.drawable.img_gas_giant_19_crop,
    R.drawable.tex_gas_giant_20 to R.drawable.img_gas_giant_20_crop,
    R.drawable.tex_gas_giant_21 to R.drawable.img_gas_giant_21_crop,
    R.drawable.tex_gas_giant_22 to R.drawable.img_gas_giant_22_crop,
    R.drawable.tex_gas_giant_23 to R.drawable.img_gas_giant_23_crop,
    R.drawable.tex_gas_giant_24 to R.drawable.img_gas_giant_24_crop,
    R.drawable.tex_gas_giant_25 to R.drawable.img_gas_giant_25_crop,
    R.drawable.tex_gas_giant_26 to R.drawable.img_gas_giant_26_crop,
    R.drawable.tex_gas_giant_27 to R.drawable.img_gas_giant_27_crop,
    R.drawable.tex_gas_giant_28 to R.drawable.img_gas_giant_28_crop,
    R.drawable.tex_gas_giant_29 to R.drawable.img_gas_giant_29_crop,
    R.drawable.tex_gas_giant_30 to R.drawable.img_gas_giant_30_crop,
    R.drawable.tex_gas_giant_31 to R.drawable.img_gas_giant_31_crop,
    R.drawable.tex_gas_giant_32 to R.drawable.img_gas_giant_32_crop,

    R.drawable.tex_ice_1 to R.drawable.img_ice_1_crop,
    R.drawable.tex_ice_2 to R.drawable.img_ice_2_crop,
    R.drawable.tex_ice_3 to R.drawable.img_ice_3_crop,
    R.drawable.tex_ice_4 to R.drawable.img_ice_4_crop,
    R.drawable.tex_ice_5 to R.drawable.img_ice_5_crop,
    R.drawable.tex_ice_6 to R.drawable.img_ice_6_crop,
    R.drawable.tex_ice_7 to R.drawable.img_ice_7_crop,
    R.drawable.tex_ice_8 to R.drawable.img_ice_8_crop,
    R.drawable.tex_ice_9 to R.drawable.img_ice_9_crop,
    R.drawable.tex_ice_10 to R.drawable.img_ice_10_crop,
    R.drawable.tex_ice_11 to R.drawable.img_ice_11_crop,
    R.drawable.tex_ice_12 to R.drawable.img_ice_12_crop,
    R.drawable.tex_ice_13 to R.drawable.img_ice_13_crop,
    R.drawable.tex_ice_14 to R.drawable.img_ice_14_crop,
    R.drawable.tex_ice_15 to R.drawable.img_ice_15_crop,
    R.drawable.tex_ice_16 to R.drawable.img_ice_16_crop,
    R.drawable.tex_ice_17 to R.drawable.img_ice_17_crop,
    R.drawable.tex_ice_18 to R.drawable.img_ice_18_crop,
    R.drawable.tex_ice_19 to R.drawable.img_ice_19_crop,
    R.drawable.tex_ice_20 to R.drawable.img_ice_20_crop,
    R.drawable.tex_ice_21 to R.drawable.img_ice_21_crop,
    R.drawable.tex_ice_22 to R.drawable.img_ice_22_crop,
    R.drawable.tex_ice_23 to R.drawable.img_ice_23_crop,
    R.drawable.tex_ice_24 to R.drawable.img_ice_24_crop,
    R.drawable.tex_ice_25 to R.drawable.img_ice_25_crop,
    R.drawable.tex_ice_26 to R.drawable.img_ice_26_crop,
    R.drawable.tex_ice_27 to R.drawable.img_ice_27_crop,
    R.drawable.tex_ice_28 to R.drawable.img_ice_28_crop,
    R.drawable.tex_ice_29 to R.drawable.img_ice_29_crop,
    R.drawable.tex_ice_30 to R.drawable.img_ice_30_crop,
    R.drawable.tex_ice_31 to R.drawable.img_ice_31_crop,
    R.drawable.tex_ice_32 to R.drawable.img_ice_32_crop,

    R.drawable.tex_martian_1 to R.drawable.img_martian_1_crop,
    R.drawable.tex_martian_2 to R.drawable.img_martian_2_crop,
    R.drawable.tex_martian_3 to R.drawable.img_martian_3_crop,
    R.drawable.tex_martian_4 to R.drawable.img_martian_4_crop,
    R.drawable.tex_martian_5 to R.drawable.img_martian_5_crop,
    R.drawable.tex_martian_6 to R.drawable.img_martian_6_crop,
    R.drawable.tex_martian_7 to R.drawable.img_martian_7_crop,
    R.drawable.tex_martian_8 to R.drawable.img_martian_8_crop,
    R.drawable.tex_martian_9 to R.drawable.img_martian_9_crop,
    R.drawable.tex_martian_10 to R.drawable.img_martian_10_crop,
    R.drawable.tex_martian_11 to R.drawable.img_martian_11_crop,
    R.drawable.tex_martian_12 to R.drawable.img_martian_12_crop,
    R.drawable.tex_martian_13 to R.drawable.img_martian_13_crop,
    R.drawable.tex_martian_14 to R.drawable.img_martian_14_crop,
    R.drawable.tex_martian_15 to R.drawable.img_martian_15_crop,
    R.drawable.tex_martian_16 to R.drawable.img_martian_16_crop,
    R.drawable.tex_martian_17 to R.drawable.img_martian_17_crop,
    R.drawable.tex_martian_18 to R.drawable.img_martian_18_crop,
    R.drawable.tex_martian_19 to R.drawable.img_martian_19_crop,
    R.drawable.tex_martian_20 to R.drawable.img_martian_20_crop,
    R.drawable.tex_martian_21 to R.drawable.img_martian_21_crop,
    R.drawable.tex_martian_22 to R.drawable.img_martian_22_crop,
    R.drawable.tex_martian_23 to R.drawable.img_martian_23_crop,
    R.drawable.tex_martian_24 to R.drawable.img_martian_24_crop,

    R.drawable.tex_oasis_1 to R.drawable.img_oasis_1_crop,
    R.drawable.tex_oasis_2 to R.drawable.img_oasis_2_crop,
    R.drawable.tex_oasis_3 to R.drawable.img_oasis_3_crop,
    R.drawable.tex_oasis_4 to R.drawable.img_oasis_4_crop,
    R.drawable.tex_oasis_5 to R.drawable.img_oasis_5_crop,
    R.drawable.tex_oasis_6 to R.drawable.img_oasis_6_crop,
    R.drawable.tex_oasis_7 to R.drawable.img_oasis_7_crop,
    R.drawable.tex_oasis_8 to R.drawable.img_oasis_8_crop,
    R.drawable.tex_oasis_9 to R.drawable.img_oasis_9_crop,
    R.drawable.tex_oasis_10 to R.drawable.img_oasis_10_crop,
    R.drawable.tex_oasis_11 to R.drawable.img_oasis_11_crop,
    R.drawable.tex_oasis_12 to R.drawable.img_oasis_12_crop,
    R.drawable.tex_oasis_13 to R.drawable.img_oasis_13_crop,
    R.drawable.tex_oasis_14 to R.drawable.img_oasis_14_crop,
    R.drawable.tex_oasis_15 to R.drawable.img_oasis_15_crop,
    R.drawable.tex_oasis_16 to R.drawable.img_oasis_16_crop,

    R.drawable.tex_oceanic_1 to R.drawable.img_oceanic_1_crop,
    R.drawable.tex_oceanic_2 to R.drawable.img_oceanic_2_crop,
    R.drawable.tex_oceanic_3 to R.drawable.img_oceanic_3_crop,
    R.drawable.tex_oceanic_4 to R.drawable.img_oceanic_4_crop,
    R.drawable.tex_oceanic_5 to R.drawable.img_oceanic_5_crop,
    R.drawable.tex_oceanic_6 to R.drawable.img_oceanic_6_crop,
    R.drawable.tex_oceanic_7 to R.drawable.img_oceanic_7_crop,
    R.drawable.tex_oceanic_8 to R.drawable.img_oceanic_8_crop,
    R.drawable.tex_oceanic_clouds_9 to R.drawable.img_oceanic_clouds_9_crop,
    R.drawable.tex_oceanic_clouds_10 to R.drawable.img_oceanic_clouds_10_crop,
    R.drawable.tex_oceanic_clouds_11 to R.drawable.img_oceanic_clouds_11_crop,
    R.drawable.tex_oceanic_clouds_12 to R.drawable.img_oceanic_clouds_12_crop,
    R.drawable.tex_oceanic_clouds_13 to R.drawable.img_oceanic_clouds_13_crop,
    R.drawable.tex_oceanic_clouds_14 to R.drawable.img_oceanic_clouds_14_crop,
    R.drawable.tex_oceanic_clouds_15 to R.drawable.img_oceanic_clouds_15_crop,
    R.drawable.tex_oceanic_clouds_16 to R.drawable.img_oceanic_clouds_16_crop,

    R.drawable.tex_primordial_1 to R.drawable.img_primordial_1_crop,
    R.drawable.tex_primordial_2 to R.drawable.img_primordial_2_crop,
    R.drawable.tex_primordial_3 to R.drawable.img_primordial_3_crop,
    R.drawable.tex_primordial_4 to R.drawable.img_primordial_4_crop,
    R.drawable.tex_primordial_5 to R.drawable.img_primordial_5_crop,
    R.drawable.tex_primordial_6 to R.drawable.img_primordial_6_crop,
    R.drawable.tex_primordial_7 to R.drawable.img_primordial_7_crop,
    R.drawable.tex_primordial_8 to R.drawable.img_primordial_8_crop,
    R.drawable.tex_primordial_9 to R.drawable.img_primordial_9_crop,
    R.drawable.tex_primordial_10 to R.drawable.img_primordial_10_crop,
    R.drawable.tex_primordial_11 to R.drawable.img_primordial_11_crop,
    R.drawable.tex_primordial_12 to R.drawable.img_primordial_12_crop,
    R.drawable.tex_primordial_13 to R.drawable.img_primordial_13_crop,
    R.drawable.tex_primordial_14 to R.drawable.img_primordial_14_crop,
    R.drawable.tex_primordial_15 to R.drawable.img_primordial_15_crop,
    R.drawable.tex_primordial_16 to R.drawable.img_primordial_16_crop,
    R.drawable.tex_primordial_17 to R.drawable.img_primordial_17_crop,
    R.drawable.tex_primordial_18 to R.drawable.img_primordial_18_crop,
    R.drawable.tex_primordial_19 to R.drawable.img_primordial_19_crop,
    R.drawable.tex_primordial_20 to R.drawable.img_primordial_20_crop,
    R.drawable.tex_primordial_21 to R.drawable.img_primordial_21_crop,
    R.drawable.tex_primordial_22 to R.drawable.img_primordial_22_crop,
    R.drawable.tex_primordial_23 to R.drawable.img_primordial_23_crop,
    R.drawable.tex_primordial_24 to R.drawable.img_primordial_24_crop,
    R.drawable.tex_primordial_25 to R.drawable.img_primordial_25_crop,
    R.drawable.tex_primordial_26 to R.drawable.img_primordial_26_crop,
    R.drawable.tex_primordial_27 to R.drawable.img_primordial_27_crop,
    R.drawable.tex_primordial_28 to R.drawable.img_primordial_28_crop,
    R.drawable.tex_primordial_29 to R.drawable.img_primordial_29_crop,
    R.drawable.tex_primordial_30 to R.drawable.img_primordial_30_crop,
    R.drawable.tex_primordial_31 to R.drawable.img_primordial_31_crop,
    R.drawable.tex_primordial_32 to R.drawable.img_primordial_32_crop,

    R.drawable.tex_rock_1 to R.drawable.img_rock_1_crop,
    R.drawable.tex_rock_2 to R.drawable.img_rock_2_crop,
    R.drawable.tex_rock_3 to R.drawable.img_rock_3_crop,
    R.drawable.tex_rock_4 to R.drawable.img_rock_4_crop,
    R.drawable.tex_rock_5 to R.drawable.img_rock_5_crop,
    R.drawable.tex_rock_6 to R.drawable.img_rock_6_crop,
    R.drawable.tex_rock_7 to R.drawable.img_rock_7_crop,
    R.drawable.tex_rock_8 to R.drawable.img_rock_8_crop,
    R.drawable.tex_rock_9 to R.drawable.img_rock_9_crop,
    R.drawable.tex_rock_10 to R.drawable.img_rock_10_crop,
    R.drawable.tex_rock_11 to R.drawable.img_rock_11_crop,
    R.drawable.tex_rock_12 to R.drawable.img_rock_12_crop,
    R.drawable.tex_rock_13 to R.drawable.img_rock_13_crop,
    R.drawable.tex_rock_14 to R.drawable.img_rock_14_crop,
    R.drawable.tex_rock_15 to R.drawable.img_rock_15_crop,
    R.drawable.tex_rock_16 to R.drawable.img_rock_16_crop,
    R.drawable.tex_rock_17 to R.drawable.img_rock_17_crop,
    R.drawable.tex_rock_18 to R.drawable.img_rock_18_crop,
    R.drawable.tex_rock_19 to R.drawable.img_rock_19_crop,
    R.drawable.tex_rock_20 to R.drawable.img_rock_20_crop,
    R.drawable.tex_rock_21 to R.drawable.img_rock_21_crop,
    R.drawable.tex_rock_22 to R.drawable.img_rock_22_crop,
    R.drawable.tex_rock_23 to R.drawable.img_rock_23_crop,
    R.drawable.tex_rock_24 to R.drawable.img_rock_24_crop,

    R.drawable.tex_swamp_1 to R.drawable.img_swamp_1_crop,
    R.drawable.tex_swamp_2 to R.drawable.img_swamp_2_crop,
    R.drawable.tex_swamp_3 to R.drawable.img_swamp_3_crop,
    R.drawable.tex_swamp_4 to R.drawable.img_swamp_4_crop,
    R.drawable.tex_swamp_5 to R.drawable.img_swamp_5_crop,
    R.drawable.tex_swamp_6 to R.drawable.img_swamp_6_crop,
    R.drawable.tex_swamp_7 to R.drawable.img_swamp_7_crop,
    R.drawable.tex_swamp_8 to R.drawable.img_swamp_8_crop,
    R.drawable.tex_swamp_clouds_9 to R.drawable.img_swamp_clouds_9_crop,
    R.drawable.tex_swamp_clouds_10 to R.drawable.img_swamp_clouds_10_crop,
    R.drawable.tex_swamp_clouds_11 to R.drawable.img_swamp_clouds_11_crop,
    R.drawable.tex_swamp_clouds_12 to R.drawable.img_swamp_clouds_12_crop,
    R.drawable.tex_swamp_clouds_13 to R.drawable.img_swamp_clouds_13_crop,
    R.drawable.tex_swamp_clouds_14 to R.drawable.img_swamp_clouds_14_crop,
    R.drawable.tex_swamp_clouds_15 to R.drawable.img_swamp_clouds_15_crop,
    R.drawable.tex_swamp_clouds_16 to R.drawable.img_swamp_clouds_16_crop,

    R.drawable.tex_terrestrial_1 to R.drawable.img_terrestrial_1_crop,
    R.drawable.tex_terrestrial_2 to R.drawable.img_terrestrial_2_crop,
    R.drawable.tex_terrestrial_3 to R.drawable.img_terrestrial_3_crop,
    R.drawable.tex_terrestrial_4 to R.drawable.img_terrestrial_4_crop,
    R.drawable.tex_terrestrial_5 to R.drawable.img_terrestrial_5_crop,
    R.drawable.tex_terrestrial_6 to R.drawable.img_terrestrial_6_crop,
    R.drawable.tex_terrestrial_7 to R.drawable.img_terrestrial_7_crop,
    R.drawable.tex_terrestrial_8 to R.drawable.img_terrestrial_8_crop,
    R.drawable.tex_terrestrial_9 to R.drawable.img_terrestrial_9_crop,
    R.drawable.tex_terrestrial_10 to R.drawable.img_terrestrial_10_crop,
    R.drawable.tex_terrestrial_11 to R.drawable.img_terrestrial_11_crop,
    R.drawable.tex_terrestrial_12 to R.drawable.img_terrestrial_12_crop,
    R.drawable.tex_terrestrial_13 to R.drawable.img_terrestrial_13_crop,
    R.drawable.tex_terrestrial_14 to R.drawable.img_terrestrial_14_crop,
    R.drawable.tex_terrestrial_15 to R.drawable.img_terrestrial_15_crop,
    R.drawable.tex_terrestrial_16 to R.drawable.img_terrestrial_16_crop,
    R.drawable.tex_terrestrial_clouds_17 to R.drawable.img_terrestrial_clouds_17_crop,
    R.drawable.tex_terrestrial_clouds_18 to R.drawable.img_terrestrial_clouds_18_crop,
    R.drawable.tex_terrestrial_clouds_19 to R.drawable.img_terrestrial_clouds_19_crop,
    R.drawable.tex_terrestrial_clouds_20 to R.drawable.img_terrestrial_clouds_20_crop,
    R.drawable.tex_terrestrial_clouds_21 to R.drawable.img_terrestrial_clouds_21_crop,
    R.drawable.tex_terrestrial_clouds_22 to R.drawable.img_terrestrial_clouds_22_crop,
    R.drawable.tex_terrestrial_clouds_23 to R.drawable.img_terrestrial_clouds_23_crop,
    R.drawable.tex_terrestrial_clouds_24 to R.drawable.img_terrestrial_clouds_24_crop,
    R.drawable.tex_terrestrial_clouds_25 to R.drawable.img_terrestrial_clouds_25_crop,
    R.drawable.tex_terrestrial_clouds_26 to R.drawable.img_terrestrial_clouds_26_crop,
    R.drawable.tex_terrestrial_clouds_27 to R.drawable.img_terrestrial_clouds_27_crop,
    R.drawable.tex_terrestrial_clouds_28 to R.drawable.img_terrestrial_clouds_28_crop,
    R.drawable.tex_terrestrial_clouds_29 to R.drawable.img_terrestrial_clouds_29_crop,
    R.drawable.tex_terrestrial_clouds_30 to R.drawable.img_terrestrial_clouds_30_crop,
    R.drawable.tex_terrestrial_clouds_31 to R.drawable.img_terrestrial_clouds_31_crop,
    R.drawable.tex_terrestrial_clouds_32 to R.drawable.img_terrestrial_clouds_32_crop,

    R.drawable.tex_venusian_1 to R.drawable.img_venusian_1_crop,
    R.drawable.tex_venusian_2 to R.drawable.img_venusian_2_crop,
    R.drawable.tex_venusian_3 to R.drawable.img_venusian_3_crop,
    R.drawable.tex_venusian_4 to R.drawable.img_venusian_4_crop,
    R.drawable.tex_venusian_5 to R.drawable.img_venusian_5_crop,
    R.drawable.tex_venusian_6 to R.drawable.img_venusian_6_crop,
    R.drawable.tex_venusian_7 to R.drawable.img_venusian_7_crop,
    R.drawable.tex_venusian_8 to R.drawable.img_venusian_8_crop,
    R.drawable.tex_venusian_9 to R.drawable.img_venusian_9_crop,
    R.drawable.tex_venusian_10 to R.drawable.img_venusian_10_crop,
    R.drawable.tex_venusian_11 to R.drawable.img_venusian_11_crop,
    R.drawable.tex_venusian_12 to R.drawable.img_venusian_12_crop,
    R.drawable.tex_venusian_13 to R.drawable.img_venusian_13_crop,
    R.drawable.tex_venusian_14 to R.drawable.img_venusian_14_crop,
    R.drawable.tex_venusian_15 to R.drawable.img_venusian_15_crop,
    R.drawable.tex_venusian_16 to R.drawable.img_venusian_16_crop,

    R.drawable.tex_volcanic_1 to R.drawable.img_volcanic_1_crop,
    R.drawable.tex_volcanic_2 to R.drawable.img_volcanic_2_crop,
    R.drawable.tex_volcanic_3 to R.drawable.img_volcanic_3_crop,
    R.drawable.tex_volcanic_4 to R.drawable.img_volcanic_4_crop,
    R.drawable.tex_volcanic_5 to R.drawable.img_volcanic_5_crop,
    R.drawable.tex_volcanic_6 to R.drawable.img_volcanic_6_crop,
    R.drawable.tex_volcanic_7 to R.drawable.img_volcanic_7_crop,
    R.drawable.tex_volcanic_8 to R.drawable.img_volcanic_8_crop,
    R.drawable.tex_volcanic_9 to R.drawable.img_volcanic_9_crop,
    R.drawable.tex_volcanic_10 to R.drawable.img_volcanic_10_crop,
    R.drawable.tex_volcanic_11 to R.drawable.img_volcanic_11_crop,
    R.drawable.tex_volcanic_12 to R.drawable.img_volcanic_12_crop,
    R.drawable.tex_volcanic_13 to R.drawable.img_volcanic_13_crop,
    R.drawable.tex_volcanic_14 to R.drawable.img_volcanic_14_crop,
    R.drawable.tex_volcanic_15 to R.drawable.img_volcanic_15_crop,
    R.drawable.tex_volcanic_16 to R.drawable.img_volcanic_16_crop,

    R.drawable.tex_wetlands_1 to R.drawable.img_wetlands_1_crop,
    R.drawable.tex_wetlands_2 to R.drawable.img_wetlands_2_crop,
    R.drawable.tex_wetlands_3 to R.drawable.img_wetlands_3_crop,
    R.drawable.tex_wetlands_4 to R.drawable.img_wetlands_4_crop,
    R.drawable.tex_wetlands_5 to R.drawable.img_wetlands_5_crop,
    R.drawable.tex_wetlands_6 to R.drawable.img_wetlands_6_crop,
    R.drawable.tex_wetlands_7 to R.drawable.img_wetlands_7_crop,
    R.drawable.tex_wetlands_8 to R.drawable.img_wetlands_8_crop,
    R.drawable.tex_wetlands_clouds_9 to R.drawable.img_wetlands_clouds_9_crop,
    R.drawable.tex_wetlands_clouds_10 to R.drawable.img_wetlands_clouds_10_crop,
    R.drawable.tex_wetlands_clouds_11 to R.drawable.img_wetlands_clouds_11_crop,
    R.drawable.tex_wetlands_clouds_12 to R.drawable.img_wetlands_clouds_12_crop,
    R.drawable.tex_wetlands_clouds_13 to R.drawable.img_wetlands_clouds_13_crop,
    R.drawable.tex_wetlands_clouds_14 to R.drawable.img_wetlands_clouds_14_crop,
    R.drawable.tex_wetlands_clouds_15 to R.drawable.img_wetlands_clouds_15_crop,
    R.drawable.tex_wetlands_clouds_16 to R.drawable.img_wetlands_clouds_16_crop,
)