package bav.astrobirthday.ui.common.opengl

import bav.astrobirthday.R
import kotlin.random.Random

sealed class TextureType(
    val minPlanetRadius: Float,
    val maxPlanetRadius: Float,
) {
    object GasGiant : TextureType(3f, 4f)
    object Ice : TextureType(0.5f, 1.5f)
    object Martian : TextureType(0.5f, 2f)
    object Primordial : TextureType(0.5f, 2f)
    object Rock : TextureType(0.25f, 1f)
    object Terrestrial : TextureType(0.5f, 2f)
    object TerrestrialClouds : TextureType(0.5f, 2f)
    object Volcanic : TextureType(0.25f, 1.5f)
    object Venusian : TextureType(0.5f, 2f)
    object Unknown : TextureType(0f, 0f) // == random

    fun getRandomRadius(random: Random): Float {
        return minPlanetRadius + (maxPlanetRadius - minPlanetRadius) * random.nextFloat()
    }

    companion object {
        val allTypes = listOf(
            GasGiant,
            Ice,
            Martian,
            Primordial,
            Rock,
            Terrestrial,
            TerrestrialClouds,
            Volcanic,
            Venusian
        )

        val middleSizeTypes = listOf(
            Martian,
            Primordial,
            Terrestrial,
            TerrestrialClouds,
            Volcanic,
            Venusian
        )

        val smallSizeTypes = listOf(
            Ice,
            Rock
        )
    }
}

val gasGiantTextures = listOf(
    R.drawable.tex_gas_giant_1,
    R.drawable.tex_gas_giant_2,
    R.drawable.tex_gas_giant_3,
    R.drawable.tex_gas_giant_4,
    R.drawable.tex_gas_giant_5,
    R.drawable.tex_gas_giant_6,
    R.drawable.tex_gas_giant_7,
    R.drawable.tex_gas_giant_8,
    R.drawable.tex_gas_giant_9,
    R.drawable.tex_gas_giant_10,
    R.drawable.tex_gas_giant_11,
    R.drawable.tex_gas_giant_12,
    R.drawable.tex_gas_giant_13,
    R.drawable.tex_gas_giant_14,
    R.drawable.tex_gas_giant_15,
    R.drawable.tex_gas_giant_16,
)

val iceTextures = listOf(
    R.drawable.tex_ice_1,
    R.drawable.tex_ice_2,
    R.drawable.tex_ice_3,
    R.drawable.tex_ice_4,
    R.drawable.tex_ice_5,
    R.drawable.tex_ice_6,
    R.drawable.tex_ice_7,
    R.drawable.tex_ice_8,
    R.drawable.tex_ice_9,
    R.drawable.tex_ice_10,
    R.drawable.tex_ice_11,
    R.drawable.tex_ice_12,
    R.drawable.tex_ice_13,
    R.drawable.tex_ice_14,
    R.drawable.tex_ice_15,
    R.drawable.tex_ice_16,
)

val martianTextures = listOf(
    R.drawable.tex_martian_1,
    R.drawable.tex_martian_2,
    R.drawable.tex_martian_3,
    R.drawable.tex_martian_4,
    R.drawable.tex_martian_5,
    R.drawable.tex_martian_6,
    R.drawable.tex_martian_7,
    R.drawable.tex_martian_8,
    R.drawable.tex_martian_9,
    R.drawable.tex_martian_10,
    R.drawable.tex_martian_11,
    R.drawable.tex_martian_12,
    R.drawable.tex_martian_13,
    R.drawable.tex_martian_14,
    R.drawable.tex_martian_15,
    R.drawable.tex_martian_16,
)

val primordialTextures = listOf(
    R.drawable.tex_primordial_1,
    R.drawable.tex_primordial_2,
    R.drawable.tex_primordial_3,
    R.drawable.tex_primordial_4,
    R.drawable.tex_primordial_5,
    R.drawable.tex_primordial_6,
    R.drawable.tex_primordial_7,
    R.drawable.tex_primordial_8,
    R.drawable.tex_primordial_9,
    R.drawable.tex_primordial_10,
    R.drawable.tex_primordial_11,
    R.drawable.tex_primordial_12,
    R.drawable.tex_primordial_13,
    R.drawable.tex_primordial_14,
    R.drawable.tex_primordial_15,
    R.drawable.tex_primordial_16,
)

val rockTextures = listOf(
    R.drawable.tex_rock_1,
    R.drawable.tex_rock_2,
    R.drawable.tex_rock_3,
    R.drawable.tex_rock_4,
    R.drawable.tex_rock_5,
    R.drawable.tex_rock_6,
    R.drawable.tex_rock_7,
    R.drawable.tex_rock_8,
    R.drawable.tex_rock_9,
    R.drawable.tex_rock_10,
    R.drawable.tex_rock_11,
    R.drawable.tex_rock_12,
    R.drawable.tex_rock_13,
    R.drawable.tex_rock_14,
    R.drawable.tex_rock_15,
    R.drawable.tex_rock_16,
)

val terrestrialTextures = listOf(
    R.drawable.tex_terrestrial_1,
    R.drawable.tex_terrestrial_2,
    R.drawable.tex_terrestrial_3,
    R.drawable.tex_terrestrial_4,
    R.drawable.tex_terrestrial_5,
    R.drawable.tex_terrestrial_6,
    R.drawable.tex_terrestrial_7,
    R.drawable.tex_terrestrial_8,
    R.drawable.tex_terrestrial_9,
    R.drawable.tex_terrestrial_10,
    R.drawable.tex_terrestrial_11,
    R.drawable.tex_terrestrial_12,
    R.drawable.tex_terrestrial_13,
    R.drawable.tex_terrestrial_14,
    R.drawable.tex_terrestrial_15,
    R.drawable.tex_terrestrial_16,
)

val terrestrialCloudsTextures = listOf(
    R.drawable.tex_terrestrial_clouds_1,
    R.drawable.tex_terrestrial_clouds_2,
    R.drawable.tex_terrestrial_clouds_3,
    R.drawable.tex_terrestrial_clouds_4,
    R.drawable.tex_terrestrial_clouds_5,
    R.drawable.tex_terrestrial_clouds_6,
    R.drawable.tex_terrestrial_clouds_7,
    R.drawable.tex_terrestrial_clouds_8,
    R.drawable.tex_terrestrial_clouds_9,
    R.drawable.tex_terrestrial_clouds_10,
    R.drawable.tex_terrestrial_clouds_11,
    R.drawable.tex_terrestrial_clouds_12,
    R.drawable.tex_terrestrial_clouds_13,
    R.drawable.tex_terrestrial_clouds_14,
    R.drawable.tex_terrestrial_clouds_15,
    R.drawable.tex_terrestrial_clouds_16,
)

val volcanicTextures = listOf(
    R.drawable.tex_volcanic_1,
    R.drawable.tex_volcanic_2,
    R.drawable.tex_volcanic_3,
    R.drawable.tex_volcanic_4,
    R.drawable.tex_volcanic_5,
    R.drawable.tex_volcanic_6,
    R.drawable.tex_volcanic_7,
    R.drawable.tex_volcanic_8,
    R.drawable.tex_volcanic_9,
    R.drawable.tex_volcanic_10,
    R.drawable.tex_volcanic_11,
    R.drawable.tex_volcanic_12,
    R.drawable.tex_volcanic_13,
    R.drawable.tex_volcanic_14,
    R.drawable.tex_volcanic_15,
    R.drawable.tex_volcanic_16,
)

val venusianTextures = listOf(
    R.drawable.tex_venusian_1,
    R.drawable.tex_venusian_2,
    R.drawable.tex_venusian_3,
    R.drawable.tex_venusian_4,
    R.drawable.tex_venusian_5,
    R.drawable.tex_venusian_6,
    R.drawable.tex_venusian_7,
    R.drawable.tex_venusian_8,
    R.drawable.tex_venusian_9,
    R.drawable.tex_venusian_10,
    R.drawable.tex_venusian_11,
    R.drawable.tex_venusian_12,
    R.drawable.tex_venusian_13,
    R.drawable.tex_venusian_14,
    R.drawable.tex_venusian_15,
    R.drawable.tex_venusian_16,
)

val satelliteTextures = listOf(
    R.drawable.tex_ice_satellite_1,
    R.drawable.tex_ice_satellite_2,
    R.drawable.tex_ice_satellite_3,
    R.drawable.tex_rock_satellite_1,
    R.drawable.tex_rock_satellite_2,
    R.drawable.tex_rock_satellite_3,
)

val ringTextures = listOf(
    R.drawable.tex_ring_50,
    R.drawable.tex_ring_51,
    R.drawable.tex_ring_52,
    R.drawable.tex_ring_53,
    R.drawable.tex_ring_54,
    R.drawable.tex_ring_55,
    R.drawable.tex_ring_56,
    R.drawable.tex_ring_57,
    R.drawable.tex_ring_58,
    R.drawable.tex_ring_59,
    R.drawable.tex_ring_60,
    R.drawable.tex_ring_61,
    R.drawable.tex_ring_62,
    R.drawable.tex_ring_63,
    R.drawable.tex_ring_64,
    R.drawable.tex_ring_65,
    R.drawable.tex_ring_66,
    R.drawable.tex_ring_67,
    R.drawable.tex_ring_68,
    R.drawable.tex_ring_69,
    R.drawable.tex_ring_70,
    R.drawable.tex_ring_71,
    R.drawable.tex_ring_72,
    R.drawable.tex_ring_73,
    R.drawable.tex_ring_74,
    R.drawable.tex_ring_75,
    R.drawable.tex_ring_76,
    R.drawable.tex_ring_77,
    R.drawable.tex_ring_78,
    R.drawable.tex_ring_79,
    R.drawable.tex_ring_80,
    R.drawable.tex_ring_81,
    R.drawable.tex_ring_82,
    R.drawable.tex_ring_83,
    R.drawable.tex_ring_84,
    R.drawable.tex_ring_85,
    R.drawable.tex_ring_86,
    R.drawable.tex_ring_87,
    R.drawable.tex_ring_88,
    R.drawable.tex_ring_89,
    R.drawable.tex_ring_90,
    R.drawable.tex_ring_91,
    R.drawable.tex_ring_92,
    R.drawable.tex_ring_93,
    R.drawable.tex_ring_94,
    R.drawable.tex_ring_95,
    R.drawable.tex_ring_96,
    R.drawable.tex_ring_97,
    R.drawable.tex_ring_98,
    R.drawable.tex_ring_99
)

val allPlanetTextures = listOf(
    gasGiantTextures,
    iceTextures,
    martianTextures,
    primordialTextures,
    rockTextures,
    terrestrialTextures,
    terrestrialCloudsTextures,
    volcanicTextures,
    venusianTextures
)

val planetImagesByTextureId = mapOf(
    R.drawable.tex_gas_giant_1 to R.drawable.img_gas_giant_1_crop,
    R.drawable.tex_gas_giant_2 to R.drawable.img_gas_giant_2_crop,
    R.drawable.tex_gas_giant_3 to R.drawable.img_gas_giant_3_crop,
    R.drawable.tex_gas_giant_4 to R.drawable.img_gas_giant_4_crop,
    R.drawable.tex_gas_giant_5 to R.drawable.img_gas_giant_5_crop,
    R.drawable.tex_gas_giant_6 to R.drawable.img_gas_giant_6_crop,
    R.drawable.tex_gas_giant_7 to R.drawable.img_gas_giant_7_crop,
    R.drawable.tex_gas_giant_8 to R.drawable.img_gas_giant_8_crop,
    R.drawable.tex_gas_giant_9 to R.drawable.img_gas_giant_9_crop,
    R.drawable.tex_gas_giant_10 to R.drawable.img_gas_giant_10_crop,
    R.drawable.tex_gas_giant_11 to R.drawable.img_gas_giant_11_crop,
    R.drawable.tex_gas_giant_12 to R.drawable.img_gas_giant_12_crop,
    R.drawable.tex_gas_giant_13 to R.drawable.img_gas_giant_13_crop,
    R.drawable.tex_gas_giant_14 to R.drawable.img_gas_giant_14_crop,
    R.drawable.tex_gas_giant_15 to R.drawable.img_gas_giant_15_crop,
    R.drawable.tex_gas_giant_16 to R.drawable.img_gas_giant_16_crop,

    R.drawable.tex_ice_1 to R.drawable.img_ice_1_crop,
    R.drawable.tex_ice_2 to R.drawable.img_ice_2_crop,
    R.drawable.tex_ice_3 to R.drawable.img_ice_3_crop,
    R.drawable.tex_ice_4 to R.drawable.img_ice_4_crop,
    R.drawable.tex_ice_5 to R.drawable.img_ice_5_crop,
    R.drawable.tex_ice_6 to R.drawable.img_ice_6_crop,
    R.drawable.tex_ice_7 to R.drawable.img_ice_7_crop,
    R.drawable.tex_ice_8 to R.drawable.img_ice_8_crop,
    R.drawable.tex_ice_9 to R.drawable.img_ice_9_crop,
    R.drawable.tex_ice_10 to R.drawable.img_ice_10_crop,
    R.drawable.tex_ice_11 to R.drawable.img_ice_11_crop,
    R.drawable.tex_ice_12 to R.drawable.img_ice_12_crop,
    R.drawable.tex_ice_13 to R.drawable.img_ice_13_crop,
    R.drawable.tex_ice_14 to R.drawable.img_ice_14_crop,
    R.drawable.tex_ice_15 to R.drawable.img_ice_15_crop,
    R.drawable.tex_ice_16 to R.drawable.img_ice_16_crop,

    R.drawable.tex_martian_1 to R.drawable.img_martian_1_crop,
    R.drawable.tex_martian_2 to R.drawable.img_martian_2_crop,
    R.drawable.tex_martian_3 to R.drawable.img_martian_3_crop,
    R.drawable.tex_martian_4 to R.drawable.img_martian_4_crop,
    R.drawable.tex_martian_5 to R.drawable.img_martian_5_crop,
    R.drawable.tex_martian_6 to R.drawable.img_martian_6_crop,
    R.drawable.tex_martian_7 to R.drawable.img_martian_7_crop,
    R.drawable.tex_martian_8 to R.drawable.img_martian_8_crop,
    R.drawable.tex_martian_9 to R.drawable.img_martian_9_crop,
    R.drawable.tex_martian_10 to R.drawable.img_martian_10_crop,
    R.drawable.tex_martian_11 to R.drawable.img_martian_11_crop,
    R.drawable.tex_martian_12 to R.drawable.img_martian_12_crop,
    R.drawable.tex_martian_13 to R.drawable.img_martian_13_crop,
    R.drawable.tex_martian_14 to R.drawable.img_martian_14_crop,
    R.drawable.tex_martian_15 to R.drawable.img_martian_15_crop,
    R.drawable.tex_martian_16 to R.drawable.img_martian_16_crop,

    R.drawable.tex_primordial_1 to R.drawable.img_primordial_1_crop,
    R.drawable.tex_primordial_2 to R.drawable.img_primordial_2_crop,
    R.drawable.tex_primordial_3 to R.drawable.img_primordial_3_crop,
    R.drawable.tex_primordial_4 to R.drawable.img_primordial_4_crop,
    R.drawable.tex_primordial_5 to R.drawable.img_primordial_5_crop,
    R.drawable.tex_primordial_6 to R.drawable.img_primordial_6_crop,
    R.drawable.tex_primordial_7 to R.drawable.img_primordial_7_crop,
    R.drawable.tex_primordial_8 to R.drawable.img_primordial_8_crop,
    R.drawable.tex_primordial_9 to R.drawable.img_primordial_9_crop,
    R.drawable.tex_primordial_10 to R.drawable.img_primordial_10_crop,
    R.drawable.tex_primordial_11 to R.drawable.img_primordial_11_crop,
    R.drawable.tex_primordial_12 to R.drawable.img_primordial_12_crop,
    R.drawable.tex_primordial_13 to R.drawable.img_primordial_13_crop,
    R.drawable.tex_primordial_14 to R.drawable.img_primordial_14_crop,
    R.drawable.tex_primordial_15 to R.drawable.img_primordial_15_crop,
    R.drawable.tex_primordial_16 to R.drawable.img_primordial_16_crop,

    R.drawable.tex_rock_1 to R.drawable.img_rock_1_crop,
    R.drawable.tex_rock_2 to R.drawable.img_rock_2_crop,
    R.drawable.tex_rock_3 to R.drawable.img_rock_3_crop,
    R.drawable.tex_rock_4 to R.drawable.img_rock_4_crop,
    R.drawable.tex_rock_5 to R.drawable.img_rock_5_crop,
    R.drawable.tex_rock_6 to R.drawable.img_rock_6_crop,
    R.drawable.tex_rock_7 to R.drawable.img_rock_7_crop,
    R.drawable.tex_rock_8 to R.drawable.img_rock_8_crop,
    R.drawable.tex_rock_9 to R.drawable.img_rock_9_crop,
    R.drawable.tex_rock_10 to R.drawable.img_rock_10_crop,
    R.drawable.tex_rock_11 to R.drawable.img_rock_11_crop,
    R.drawable.tex_rock_12 to R.drawable.img_rock_12_crop,
    R.drawable.tex_rock_13 to R.drawable.img_rock_13_crop,
    R.drawable.tex_rock_14 to R.drawable.img_rock_14_crop,
    R.drawable.tex_rock_15 to R.drawable.img_rock_15_crop,
    R.drawable.tex_rock_16 to R.drawable.img_rock_16_crop,

    R.drawable.tex_terrestrial_1 to R.drawable.img_terrestrial_1_crop,
    R.drawable.tex_terrestrial_2 to R.drawable.img_terrestrial_2_crop,
    R.drawable.tex_terrestrial_3 to R.drawable.img_terrestrial_3_crop,
    R.drawable.tex_terrestrial_4 to R.drawable.img_terrestrial_4_crop,
    R.drawable.tex_terrestrial_5 to R.drawable.img_terrestrial_5_crop,
    R.drawable.tex_terrestrial_6 to R.drawable.img_terrestrial_6_crop,
    R.drawable.tex_terrestrial_7 to R.drawable.img_terrestrial_7_crop,
    R.drawable.tex_terrestrial_8 to R.drawable.img_terrestrial_8_crop,
    R.drawable.tex_terrestrial_9 to R.drawable.img_terrestrial_9_crop,
    R.drawable.tex_terrestrial_10 to R.drawable.img_terrestrial_10_crop,
    R.drawable.tex_terrestrial_11 to R.drawable.img_terrestrial_11_crop,
    R.drawable.tex_terrestrial_12 to R.drawable.img_terrestrial_12_crop,
    R.drawable.tex_terrestrial_13 to R.drawable.img_terrestrial_13_crop,
    R.drawable.tex_terrestrial_14 to R.drawable.img_terrestrial_14_crop,
    R.drawable.tex_terrestrial_15 to R.drawable.img_terrestrial_15_crop,
    R.drawable.tex_terrestrial_16 to R.drawable.img_terrestrial_16_crop,

    R.drawable.tex_terrestrial_clouds_1 to R.drawable.img_terrestrial_clouds_1_crop,
    R.drawable.tex_terrestrial_clouds_2 to R.drawable.img_terrestrial_clouds_2_crop,
    R.drawable.tex_terrestrial_clouds_3 to R.drawable.img_terrestrial_clouds_3_crop,
    R.drawable.tex_terrestrial_clouds_4 to R.drawable.img_terrestrial_clouds_4_crop,
    R.drawable.tex_terrestrial_clouds_5 to R.drawable.img_terrestrial_clouds_5_crop,
    R.drawable.tex_terrestrial_clouds_6 to R.drawable.img_terrestrial_clouds_6_crop,
    R.drawable.tex_terrestrial_clouds_7 to R.drawable.img_terrestrial_clouds_7_crop,
    R.drawable.tex_terrestrial_clouds_8 to R.drawable.img_terrestrial_clouds_8_crop,
    R.drawable.tex_terrestrial_clouds_9 to R.drawable.img_terrestrial_clouds_9_crop,
    R.drawable.tex_terrestrial_clouds_10 to R.drawable.img_terrestrial_clouds_10_crop,
    R.drawable.tex_terrestrial_clouds_11 to R.drawable.img_terrestrial_clouds_11_crop,
    R.drawable.tex_terrestrial_clouds_12 to R.drawable.img_terrestrial_clouds_12_crop,
    R.drawable.tex_terrestrial_clouds_13 to R.drawable.img_terrestrial_clouds_13_crop,
    R.drawable.tex_terrestrial_clouds_14 to R.drawable.img_terrestrial_clouds_14_crop,
    R.drawable.tex_terrestrial_clouds_15 to R.drawable.img_terrestrial_clouds_15_crop,
    R.drawable.tex_terrestrial_clouds_16 to R.drawable.img_terrestrial_clouds_16_crop,

    R.drawable.tex_volcanic_1 to R.drawable.img_volcanic_1_crop,
    R.drawable.tex_volcanic_2 to R.drawable.img_volcanic_2_crop,
    R.drawable.tex_volcanic_3 to R.drawable.img_volcanic_3_crop,
    R.drawable.tex_volcanic_4 to R.drawable.img_volcanic_4_crop,
    R.drawable.tex_volcanic_5 to R.drawable.img_volcanic_5_crop,
    R.drawable.tex_volcanic_6 to R.drawable.img_volcanic_6_crop,
    R.drawable.tex_volcanic_7 to R.drawable.img_volcanic_7_crop,
    R.drawable.tex_volcanic_8 to R.drawable.img_volcanic_8_crop,
    R.drawable.tex_volcanic_9 to R.drawable.img_volcanic_9_crop,
    R.drawable.tex_volcanic_10 to R.drawable.img_volcanic_10_crop,
    R.drawable.tex_volcanic_11 to R.drawable.img_volcanic_11_crop,
    R.drawable.tex_volcanic_12 to R.drawable.img_volcanic_12_crop,
    R.drawable.tex_volcanic_13 to R.drawable.img_volcanic_13_crop,
    R.drawable.tex_volcanic_14 to R.drawable.img_volcanic_14_crop,
    R.drawable.tex_volcanic_15 to R.drawable.img_volcanic_15_crop,
    R.drawable.tex_volcanic_16 to R.drawable.img_volcanic_16_crop,

    R.drawable.tex_venusian_1 to R.drawable.img_venusian_1_crop,
    R.drawable.tex_venusian_2 to R.drawable.img_venusian_2_crop,
    R.drawable.tex_venusian_3 to R.drawable.img_venusian_3_crop,
    R.drawable.tex_venusian_4 to R.drawable.img_venusian_4_crop,
    R.drawable.tex_venusian_5 to R.drawable.img_venusian_5_crop,
    R.drawable.tex_venusian_6 to R.drawable.img_venusian_6_crop,
    R.drawable.tex_venusian_7 to R.drawable.img_venusian_7_crop,
    R.drawable.tex_venusian_8 to R.drawable.img_venusian_8_crop,
    R.drawable.tex_venusian_9 to R.drawable.img_venusian_9_crop,
    R.drawable.tex_venusian_10 to R.drawable.img_venusian_10_crop,
    R.drawable.tex_venusian_11 to R.drawable.img_venusian_11_crop,
    R.drawable.tex_venusian_12 to R.drawable.img_venusian_12_crop,
    R.drawable.tex_venusian_13 to R.drawable.img_venusian_13_crop,
    R.drawable.tex_venusian_14 to R.drawable.img_venusian_14_crop,
    R.drawable.tex_venusian_15 to R.drawable.img_venusian_15_crop,
    R.drawable.tex_venusian_16 to R.drawable.img_venusian_16_crop,
)